# Create a spotify application here:
# https://developer.spotify.com/dashboard/applications
spotify-id: "" # Your spotify app client ID.
spotify-secret: "" # Your spotify app secret.

# Location of the music library. Relative to the (if specified) working directory.
library-folder: "./Music"

# The Piped API instance to use. No trailing slash.
piped-api: "https://pipedapi.kavin.rocks"

# The command to use for downloading media. Output should be made to stdout. '%URL%' is replaced with the URL to download.
ytdl-command: ["yt-dlp", "%URL%", "-o", "-"]
